### ISSUE TITLE
Error when charset is in response content-type header

### ISSUE THREAD

**Issue by rhinoman** [Azure/fetch-event-source#1]
My spring-boot application adds the charset automatically, on an event I get a closed connection and the following error:

Error: Expected content-type to be text/event-stream, Actual: text/event-stream;charset=UTF-8

**Comment by vishwam** [comment]
Hi @rhinoman, apologies for the late response. Your changes looked good, I just had one minor nit to account for content-type being undefined, so I made the changes and published v1.0.1. Please let me know if that addresses your scenario.

**Comment by rhinoman** [comment]
That fixes it, thanks!
