### ISSUE TITLE
connect disconnected after change Chrome Tabs

### ISSUE THREAD

**Issue by advancedweld** [Azure/fetch-event-source#75]
![image](https://github.com/Azure/fetch-event-source/assets/35281187/03e15ae1-c8a3-4c9e-916a-118033ea5f1c)
As u can see, when I CHANGE the tab page to another page ,the SSE will  be CANCELED , and when I active the page, the SSE will reconnect .
I dont want SSE be canceled when change tab pages ,how can I to?

**Comment by mandarBadve** [comment]
Try setting 
**openWhenHidden: true**

**Comment by saarangtiwari** [comment]
setting `openWhenHidden: true` has resolved this issue.

**Comment by vikyw89** [comment]
why is this not the default value
