### ISSUE TITLE
Fetch never aborted during network error even when calling abort on inputSignal

### ISSUE THREAD

**Issue by owodunni** [Azure/fetch-event-source#87]
Hello,

We have a streaming API that I use fetch-event-source to work with. However I have a issue, my code tries to cancel fetchEventSource when there is an error.

```
          const controller = new AbortController();

          fetchEventSource(`${this.baseUrl}api/v1/${endpoint}`, {
            signal: controller.signal ,
            method: "POST",
            headers: {
              ...headers,
              "Content-Type": "application/json",
              Accept: "text/event-stream",
            },
            body: payload,

              onerror: (event) => {
              controller.abort();
              ...
              }
              });
```

The result looks like this when I set the browser to be offline.
![Image](https://github.com/user-attachments/assets/1d8a9f6b-a970-437e-a2ad-746d3e55fadc)

**Comment by owodunni** [comment]
I needed to throw in onerror!

**Comment by lizihanglove** [comment]
> I needed to throw in onerror!

what a genius action!

**Comment by piotr-cz** [comment]
It's described in README:

https://github.com/Azure/fetch-event-source/blob/a0529492576e094374602f24d5e64b3a271b4576/README.md?plain=1#L83-L90
